// <auto-generated />
using DartVerwaltung.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DartVerwaltung.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250826121504_changes")]
    partial class changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("DartVerwaltung.Database.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Alter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Austrittsdatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beruf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Eintrittsdatum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Familienstand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Geburtstag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Informationen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profilbild")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
